// MySqlDS.h : Declaration of the CMySqlSource
#ifndef __CMySqlSource_H_
#define __CMySqlSource_H_
#include "resource.h"       // main symbols
#include "MySqlRS.h"
#include "DatasrcExImpl.h"
#include "MySqlSess.h"

/////////////////////////////////////////////////////////////////////////////
// CDataSource

class ATL_NO_VTABLE CMySqlSource : 
	public CComObjectRootEx<CComSingleThreadModel>,
	public CComCoClass<CMySqlSource, &CLSID_MySql>,
	public IDBCreateSessionImpl<CMySqlSource, CMySqlSession>,
	public IDBInitializeImpl<CMySqlSource>,
	public IDBPropertiesImpl<CMySqlSource>,
	public IPersistImpl<CMySqlSource>,
	public IInternalConnectionImpl<CMySqlSource>,
	public IDBInfoImpl<CMySqlSource>,
	public IConnectionSource
{
public:
	HRESULT FinalConstruct()
	{
		return FInit();
	}
	// IConnectionSource
	STDMETHOD(GetConnection)(void **ppConnection);
	STDMETHOD(ReleaseConnection)(void *pConnection);

	// IDBPropertiesImpl::GetProperties
	STDMETHOD(GetProperties)(ULONG cPropertySets,
							 const DBPROPIDSET rgPropertySets[],
							 ULONG *pcProperties,
							 DBPROPSET **prgProperties);
	STDMETHOD(SetProperties)(ULONG cPropertySets, DBPROPSET  rgPropertySets[]);
	HRESULT GetCurrentCatalog(VARIANT *pvCatalog);
	HRESULT SetCurrentCatalog(VARIANT *pvCatalog);
	virtual HRESULT OnPropertyChanged(ULONG iCurSet, DBPROP *pDBProp);

DECLARE_REGISTRY_RESOURCEID(IDR_MYSQL)
BEGIN_PROPSET_MAP(CMySqlSource)
	BEGIN_PROPERTY_SET(DBPROPSET_DATASOURCE)
		PROPERTY_INFO_ENTRY_VALUE(CURRENTCATALOG, OLESTR(""))
	END_PROPERTY_SET(DBPROPSET_DATASOURCE)
	BEGIN_PROPERTY_SET(DBPROPSET_DATASOURCEINFO)
		PROPERTY_INFO_ENTRY_VALUE(ACTIVESESSIONS, 0)
		PROPERTY_INFO_ENTRY_VALUE(COLUMNDEFINITION, DBPROPVAL_CD_NOTNULL)
		PROPERTY_INFO_ENTRY_VALUE(DATASOURCEREADONLY, VARIANT_FALSE)
		PROPERTY_INFO_ENTRY_VALUE(BYREFACCESSORS, VARIANT_FALSE)
		PROPERTY_INFO_ENTRY_VALUE(OUTPUTPARAMETERAVAILABILITY, DBPROPVAL_OA_NOTSUPPORTED)
		PROPERTY_INFO_ENTRY_VALUE(PROVIDEROLEDBVER, OLESTR("01.00"))
		PROPERTY_INFO_ENTRY(USERNAME)
		PROPERTY_INFO_ENTRY_VALUE(DBMSNAME, OLESTR("MySQL Server"))
		PROPERTY_INFO_ENTRY_VALUE(DSOTHREADMODEL, DBPROPVAL_RT_SINGLETHREAD | DBPROPVAL_RT_APTMTTHREAD)
		PROPERTY_INFO_ENTRY_VALUE(SQLSUPPORT, DBPROPVAL_SQL_ANSI92_INTERMEDIATE)
		PROPERTY_INFO_ENTRY_VALUE(TABLETERM, OLESTR("table"))
		PROPERTY_INFO_ENTRY_VALUE(SCHEMATERM, OLESTR("owner"))
		PROPERTY_INFO_ENTRY_VALUE(CATALOGTERM, OLESTR("database"))
		PROPERTY_INFO_ENTRY_VALUE(CATALOGLOCATION, DBPROPVAL_CL_START)
		PROPERTY_INFO_ENTRY_VALUE(CATALOGUSAGE, DBPROPVAL_CU_DML_STATEMENTS)
		PROPERTY_INFO_ENTRY_VALUE(SCHEMAUSAGE, DBPROPVAL_SU_DML_STATEMENTS)
		PROPERTY_INFO_ENTRY_VALUE(SUBQUERIES, 0)
		PROPERTY_INFO_ENTRY_VALUE(SUPPORTEDTXNDDL, DBPROPVAL_TC_NONE)
		PROPERTY_INFO_ENTRY_VALUE(SUPPORTEDTXNISOLEVELS, 0)
		PROPERTY_INFO_ENTRY_VALUE(SUPPORTEDTXNISORETAIN, 0)
		PROPERTY_INFO_ENTRY_VALUE(ASYNCTXNABORT, VARIANT_FALSE)
		PROPERTY_INFO_ENTRY_VALUE(ASYNCTXNCOMMIT, VARIANT_FALSE)
		PROPERTY_INFO_ENTRY_VALUE(MAXINDEXSIZE, 0)
		PROPERTY_INFO_ENTRY_VALUE(MAXROWSIZE, 16384)
		PROPERTY_INFO_ENTRY_VALUE(MAXROWSIZEINCLUDESBLOB, VARIANT_TRUE)
		PROPERTY_INFO_ENTRY_VALUE(MAXTABLESINSELECT, 0)
		PROPERTY_INFO_ENTRY_VALUE(OLEOBJECTS, 0)
		PROPERTY_INFO_ENTRY_VALUE(ORDERBYCOLUMNSINSELECT, VARIANT_FALSE)
		PROPERTY_INFO_ENTRY_VALUE(PROCEDURETERM, OLESTR("stored proc"))
		PROPERTY_INFO_ENTRY_VALUE(PERSISTENTIDTYPE, DBPROPVAL_PT_NAME)
		PROPERTY_INFO_ENTRY_VALUE(PROVIDERNAME, OLESTR("prov.dll"))
		PROPERTY_INFO_ENTRY_VALUE(MULTIPLERESULTS, DBPROPVAL_MR_NOTSUPPORTED)
		PROPERTY_INFO_ENTRY_VALUE(NULLCOLLATION, DBPROPVAL_NC_LOW)
		PROPERTY_INFO_ENTRY_VALUE(CONCATNULLBEHAVIOR, DBPROPVAL_CB_NON_NULL)
		PROPERTY_INFO_ENTRY_VALUE(IDENTIFIERCASE, DBPROPVAL_IC_MIXED)
		PROPERTY_INFO_ENTRY_VALUE(GROUPBY, DBPROPVAL_GB_EQUALS_SELECT)
		PROPERTY_INFO_ENTRY_VALUE(HETEROGENEOUSTABLES, 0)
		PROPERTY_INFO_ENTRY_VALUE(MAXROWS, 0)
	END_PROPERTY_SET(DBPROPSET_DATASOURCEINFO)
	BEGIN_PROPERTY_SET(DBPROPSET_DBINIT)
		PROPERTY_INFO_ENTRY(INIT_DATASOURCE)
		//PROPERTY_INFO_ENTRY(INIT_LOCATION)
		PROPERTY_INFO_ENTRY(INIT_CATALOG)
		PROPERTY_INFO_ENTRY(AUTH_PASSWORD)
		PROPERTY_INFO_ENTRY(AUTH_USERID)
		PROPERTY_INFO_ENTRY(INIT_HWND)
		PROPERTY_INFO_ENTRY(INIT_LCID)
		PROPERTY_INFO_ENTRY(INIT_PROMPT)
		PROPERTY_INFO_ENTRY(INIT_PROVIDERSTRING)
	END_PROPERTY_SET(DBPROPSET_DBINIT)
	CHAIN_PROPERTY_SET(CProvCommand)
END_PROPSET_MAP()
BEGIN_COM_MAP(CMySqlSource)
	COM_INTERFACE_ENTRY(IDBInfo)
	COM_INTERFACE_ENTRY(IDBCreateSession)
	COM_INTERFACE_ENTRY(IDBInitialize)
	COM_INTERFACE_ENTRY(IDBProperties)
	COM_INTERFACE_ENTRY(IPersist)
	COM_INTERFACE_ENTRY(IInternalConnection)
	COM_INTERFACE_ENTRY(IConnectionSource)
END_COM_MAP()
public:
};
#endif //__CMySqlSource_H_
